version: '3'

services:
  jupyterlab:
    build: ./
    image: lab
    container_name: jupyter-lab
    volumes:
     - ./:/app
    ports:
      - "8888:8888"
    environment:
      - DEV=1
      - POSTGRES_URI=postgres://caltrans:secret@postgres:5432/caltrans
    command: "jupyter-lab --no-browser --ip=\"*\" --allow-root --port=8888 --NotebookApp.notebook_dir=/app --NotebookApp.terminado_settings='{\"shell_command\": [\"bash\"]}' --LabApp.token=\"\" --LabApp.password=\"\""
  voila:
    build: ./
    image: voila
    container_name: voila
    volumes:
     - ./:/app
    ports:
      - "8080:8080"
  postgres:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=caltrans
      - POSTGRES_PASSWORD=secret
