site_name: TransitStacks
nav:
    - Home: index.md
    - Getting started: starting.md
    - Usage: usage.md
    - API: api.md
    - Development: developing.md
theme: material
plugins:
- search
- mkdocstrings